    services:
        db:
            image: postgres:16
            container_name: books_pg
            restart: unless-stopped
            environment:
                POSTGRES_DB: dbs
                POSTGRES_USER:  user
                POSTGRES_PASSWORD: secret
            ports:
                - "5432:5432"
            volumes:
                - books_data:/var/lib/postgresql/data
            healthcheck:
                test: ["CMD-SHELL", "pg_isready -U booksuser -d booksdb"]
                interval: 5s
                timeout: 3s
                retries: 18
    volumes:
        books_data:
    

      
        