services:
  db:
    image: postgres:16
    container_name: owners_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: ownersdb
      POSTGRES_USER: ownersuser
      POSTGRES_PASSWORD: supersecret
    ports:
      - "5432:5432"
    volumes:
      - owners_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ownersuser -d ownersdb"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  owners_data: