services:
  db: 
    image: postgres:16
    container_name: veterinaria_pg 
    restart: unless-stopped
    environment:
      POSTGRES_DB: veterinaria_db
      POSTGRES_USER: veterinaria_user
      POSTGRES_PASSWORD: supersecret
    ports: 
      - "5432:5432"
    volumes:
      - veterinaria_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U veterinaria_user -d veterinaria_db"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  veterinaria_data: 